# Generated by Django 4.2 on 2023-07-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_usuario_cep_usuario_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, to='app.usuario'),
        ),
    ]
