# Generated by Django 4.2 on 2023-07-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usuario_cep_usuario_cidade_usuario_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Atendimento',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-id'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
