# Generated by Django 4.2 on 2023-07-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_funcionario_atendimento_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['-id'], 'verbose_name': 'Atendimento', 'verbose_name_plural': 'Atendimentos'},
        ),
    ]
