# Generated by Django 4.2 on 2023-07-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_categoria_alter_atendimento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='categoria',
            field=models.ManyToManyField(to='app.categoria'),
        ),
    ]
