# Generated by Django 4.2 on 2023-07-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_funcionario_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
