# Generated by Django 4.2 on 2023-07-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_categoria_funcionario_categorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='CEP',
            new_name='cep',
        ),
    ]
